name: Implementation Interoperability Report

on:
  push:
    branches:
      - main

jobs:
  publish-test-results:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Deploy test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
